services:
  database:
    image: postgres:15-alpine
    container_name: oncomente-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: oncomente
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: oncomente-auth
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://database:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: adminpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - database