services:
  database:
    image: postgres:15-alpine
    container_name: oncomente-db
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: Em4nu3l!@%23
      POSTGRES_DB: oncomente
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: